[general]
# import = ["~/.config/alacritty/gruvbox.toml"]
import = ["~/.config/alacritty/gruvbox_light.toml"]
live_config_reload = true


[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 10

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.normal]
# family = "Cozette"
family = "Fira Code"
# family = "HackNerdFont"
# style = "Medium"

# [font.bold]
# family = "CozetteHiDpi"
# style = "Bold"

# [font.bold_italic]
# family = "CozetteHiDpi"
# style = "Bold Italic"

# [font.italic]
# family = "CozetteHiDpi"
# style = "Italic"


[hints]
alphabet = "ntesiroamglpufyw;q"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi|~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Copy"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi|~Search"
mods = "Alt"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Up"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "E"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "N"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "O"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Up"
key = "Up"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "Down"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "Left"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "Right"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key6"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "High"
key = "N"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Middle"
key = "M"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Low"
key = "O"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SemanticLeft"
key = "B"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRight"
key = "W"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "J"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "WordLeft"
key = "B"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRight"
key = "W"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRightEnd"
key = "J"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "Bracket"
key = "Key5"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "H"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "H"
mode = "Vi|~Search"
mods = "Shift"

[mouse]
hide_when_typing = true


[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = false
opacity = 0.95
